version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CF-stack-for-soil-moisture-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fpymhq74hbu9"
s3_prefix = "CF-stack-for-soil-moisture-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
